// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo1KPA1g9t7oX54KrM5R4y0l9--uJpPa0',
    appId: '1:672848913759:web:4f24e6f59dae0d4c02c2ea',
    messagingSenderId: '672848913759',
    projectId: 'bookhive-3977a',
    authDomain: 'bookhive-3977a.firebaseapp.com',
    databaseURL: 'https://bookhive-3977a-default-rtdb.firebaseio.com',
    storageBucket: 'bookhive-3977a.firebasestorage.app',
    measurementId: 'G-C1CTVLR5F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNl3XyyFroMTADtuCsR-maR7zcnxUQnY',
    appId: '1:672848913759:android:a39489b9d5d55d4802c2ea',
    messagingSenderId: '672848913759',
    projectId: 'bookhive-3977a',
    databaseURL: 'https://bookhive-3977a-default-rtdb.firebaseio.com',
    storageBucket: 'bookhive-3977a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArMZeeIRaUmMQSZrKVa8shyQCU5o_imvI',
    appId: '1:672848913759:ios:bb2b7ff9f021ee8302c2ea',
    messagingSenderId: '672848913759',
    projectId: 'bookhive-3977a',
    databaseURL: 'https://bookhive-3977a-default-rtdb.firebaseio.com',
    storageBucket: 'bookhive-3977a.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArMZeeIRaUmMQSZrKVa8shyQCU5o_imvI',
    appId: '1:672848913759:ios:bb2b7ff9f021ee8302c2ea',
    messagingSenderId: '672848913759',
    projectId: 'bookhive-3977a',
    databaseURL: 'https://bookhive-3977a-default-rtdb.firebaseio.com',
    storageBucket: 'bookhive-3977a.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo1KPA1g9t7oX54KrM5R4y0l9--uJpPa0',
    appId: '1:672848913759:web:fb110a377ce370bc02c2ea',
    messagingSenderId: '672848913759',
    projectId: 'bookhive-3977a',
    authDomain: 'bookhive-3977a.firebaseapp.com',
    databaseURL: 'https://bookhive-3977a-default-rtdb.firebaseio.com',
    storageBucket: 'bookhive-3977a.firebasestorage.app',
    measurementId: 'G-HXYXXCEQJ4',
  );
}
